REQUIRED_STUDENT_IMPORT_COLUMNS = ("nombre", "apellido", "email")
OPTIONAL_STUDENT_IMPORT_COLUMNS = ("password",)
STUDENT_IMPORT_COLUMNS = REQUIRED_STUDENT_IMPORT_COLUMNS + OPTIONAL_STUDENT_IMPORT_COLUMNS

STUDENT_IMPORT_TEMPLATE_FILENAME = "plantilla_importacion_estudiantes_siep.xlsx"
