# Generated by Django 5.1.8 on 2026-06-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accessrequest'),
        ('users', '0002_initial'),
    ]

    operations = [
    ]
