from __future__ import annotations

from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = ROOT / "docs" / "character-modular-raw"
OUT_DIR = ROOT / "docs" / "character-modular-processed"
FRAME_SIZE = (64, 96)
SHEET_SIZE = (FRAME_SIZE[0] * 3, FRAME_SIZE[1] * 3)

NAME_OVERRIDES = {
    "hair/oscuro1.png": "hair/hair_short_black_back.png",
    "hair/oscuro2.png": "hair/hair_short_black_front.png",
}

# Calibración fase C (medida sobre col 1 de cada fila):
#   - El cuerpo crudo trae los pies a alturas distintas por fila (90/77/60):
#     al cambiar de dirección el avatar "saltaba". Se alinean los pies a y=90.
#   - Cara y pelo siguen el delta del cuerpo de su fila y además se asientan
#     sobre el cráneo (la "gorra" frontal termina en la línea de cejas ~y41;
#     la masa trasera cubre el cráneo en la fila de espalda).
ROW_OFFSETS = {
    "body/body_orientadora_purple.png": {1: (0, 13), 2: (0, 30)},
    "face/face_neutral.png": {0: (0, -18), 1: (0, 5)},
    "face/face_calm.png": {0: (0, -8), 1: (0, 10)},
    "face/face_worried.png": {0: (0, -8), 1: (0, 8)},
    "hair/hair_short_black_back.png": {0: (0, -10), 1: (0, 4), 2: (0, 14)},
    "hair/hair_short_black_front.png": {0: (0, -19), 1: (0, -2)},
    "hair/hair_long_brown_back.png": {0: (0, -11), 1: (0, 8), 2: (0, 21)},
    "hair/hair_long_brown_front.png": {0: (0, -12), 1: (0, 4), 2: (0, 25)},
    "hair/hair_tied_brown_back.png": {0: (0, -16), 1: (0, 2), 2: (0, 19)},
    "hair/hair_tied_brown_front.png": {0: (0, -21), 1: (0, -4), 2: (0, 7)},
    "hair/hair_red_back.png": {0: (0, -25), 1: (0, 4), 2: (0, 31)},
    "hair/hair_red_front.png": {0: (0, -19), 1: (0, 3), 2: (0, 20)},
}

# Compresión vertical por fila (sx, sy) ANTES del offset: las "gorras" tied y
# red vienen dibujadas para una cabeza más alta que la del cuerpo; sin esto
# taparían los ojos o flotarían media cabeza por encima.
ROW_SCALES = {
    "hair/hair_tied_brown_front.png": {0: (1.0, 0.72)},
    "hair/hair_red_front.png": {0: (1.0, 0.65)},
}


def output_name(path: Path) -> Path:
    rel = path.relative_to(RAW_DIR).as_posix()
    if rel in NAME_OVERRIDES:
        return OUT_DIR / NAME_OVERRIDES[rel]
    return OUT_DIR / rel.replace("_raw", "")


def remove_connected_light_background(image: Image.Image) -> Image.Image:
    rgba = np.array(image.convert("RGBA"), dtype=np.uint8)
    rgb = rgba[:, :, :3]
    maxc = rgb.max(axis=2)
    minc = rgb.min(axis=2)

    # Background generated by ChatGPT is a near-white/near-gray checkerboard.
    # We only remove candidate pixels connected to the image border so internal
    # light details such as eye whites or shirt highlights can survive.
    candidate = (
        (rgb[:, :, 0] >= 236)
        & (rgb[:, :, 1] >= 236)
        & (rgb[:, :, 2] >= 236)
        & ((maxc - minc) <= 24)
    )

    h, w = candidate.shape
    background = np.zeros_like(candidate, dtype=bool)
    queue: deque[tuple[int, int]] = deque()

    for x in range(w):
        if candidate[0, x]:
            background[0, x] = True
            queue.append((0, x))
        if candidate[h - 1, x] and not background[h - 1, x]:
            background[h - 1, x] = True
            queue.append((h - 1, x))
    for y in range(h):
        if candidate[y, 0] and not background[y, 0]:
            background[y, 0] = True
            queue.append((y, 0))
        if candidate[y, w - 1] and not background[y, w - 1]:
            background[y, w - 1] = True
            queue.append((y, w - 1))

    while queue:
        y, x = queue.popleft()
        for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
            if 0 <= ny < h and 0 <= nx < w and candidate[ny, nx] and not background[ny, nx]:
                background[ny, nx] = True
                queue.append((ny, nx))

    rgba[background, 3] = 0
    rgba[background, :3] = 0
    return Image.fromarray(rgba, "RGBA")


def shift_row_frames(
    sheet: Image.Image,
    offsets: dict[int, tuple[int, int]],
    scales: dict[int, tuple[float, float]] | None = None,
) -> Image.Image:
    shifted = Image.new("RGBA", SHEET_SIZE, (0, 0, 0, 0))
    frame_w, frame_h = FRAME_SIZE

    for row in range(3):
        dx, dy = offsets.get(row, (0, 0))
        sx, sy = (scales or {}).get(row, (1.0, 1.0))
        for col in range(3):
            frame_box = (
                col * frame_w,
                row * frame_h,
                (col + 1) * frame_w,
                (row + 1) * frame_h,
            )
            frame = sheet.crop(frame_box)
            if (sx, sy) != (1.0, 1.0):
                new_w = max(1, round(frame_w * sx))
                new_h = max(1, round(frame_h * sy))
                scaled = frame.resize((new_w, new_h), Image.Resampling.LANCZOS)
                frame = Image.new("RGBA", FRAME_SIZE, (0, 0, 0, 0))
                # Escala anclada al centro del frame; el offset hace el resto.
                frame.alpha_composite(scaled, ((frame_w - new_w) // 2, (frame_h - new_h) // 2))
            target = Image.new("RGBA", FRAME_SIZE, (0, 0, 0, 0))
            target.alpha_composite(frame, (dx, dy))
            shifted.alpha_composite(target, (col * frame_w, row * frame_h))

    return shifted


def process_image(path: Path) -> Image.Image:
    cleaned = remove_connected_light_background(Image.open(path))
    sheet = cleaned.resize(SHEET_SIZE, Image.Resampling.LANCZOS)

    rgba = np.array(sheet, dtype=np.uint8)
    transparent = rgba[:, :, 3] < 32
    rgba[transparent, 3] = 0
    rgba[transparent, :3] = 0
    processed = Image.fromarray(rgba, "RGBA")
    rel = output_name(path).relative_to(OUT_DIR).as_posix()
    return shift_row_frames(processed, ROW_OFFSETS.get(rel, {}), ROW_SCALES.get(rel))


def make_preview(paths: list[Path]) -> None:
    scale = 3
    tile_w = SHEET_SIZE[0] * scale
    tile_h = SHEET_SIZE[1] * scale + 22
    cols = 3
    rows = (len(paths) + cols - 1) // cols
    preview = Image.new("RGBA", (tile_w * cols, tile_h * rows), (16, 18, 28, 255))
    draw = ImageDraw.Draw(preview)

    for idx, path in enumerate(paths):
        sheet = Image.open(path).convert("RGBA").resize((tile_w, SHEET_SIZE[1] * scale), Image.Resampling.NEAREST)
        x = (idx % cols) * tile_w
        y = (idx // cols) * tile_h
        preview.alpha_composite(sheet, (x, y))
        label = path.relative_to(OUT_DIR).as_posix()
        draw.text((x + 6, y + SHEET_SIZE[1] * scale + 4), label, fill=(220, 220, 235, 255))

    preview.save(OUT_DIR / "_preview.png")


def load_layer(relative: str) -> Image.Image:
    return Image.open(OUT_DIR / relative).convert("RGBA")


def compose_avatar(hair_id: str, face_id: str) -> Image.Image:
    """Composición por fila (igual que el runtime Phaser):
    frente/lado → pelo-atrás DETRÁS del cuerpo; espalda → pelo-atrás encima."""
    body = load_layer("body/body_orientadora_purple.png")
    back = load_layer(f"hair/hair_{hair_id}_back.png")
    face = load_layer(f"face/face_{face_id}.png")
    front = load_layer(f"hair/hair_{hair_id}_front.png")

    sheet = Image.new("RGBA", SHEET_SIZE, (0, 0, 0, 0))
    frame_w, frame_h = FRAME_SIZE
    for row in range(3):
        order = (back, body, face, front) if row < 2 else (body, back, face, front)
        for col in range(3):
            box = (col * frame_w, row * frame_h, (col + 1) * frame_w, (row + 1) * frame_h)
            tile = Image.new("RGBA", FRAME_SIZE, (0, 0, 0, 0))
            for layer_sheet in order:
                tile.alpha_composite(layer_sheet.crop(box))
            sheet.alpha_composite(tile, (box[0], box[1]))
    return sheet


def make_composite_preview() -> None:
    combos = [
        ("short_black", "neutral"),
        ("long_brown", "calm"),
        ("tied_brown", "neutral"),
        ("red", "worried"),
    ]
    scale = 3
    tile_w = SHEET_SIZE[0] * scale
    tile_h = SHEET_SIZE[1] * scale + 22
    preview = Image.new("RGBA", (tile_w * 2, tile_h * 2), (16, 18, 28, 255))
    draw = ImageDraw.Draw(preview)

    for idx, (hair, face) in enumerate(combos):
        sheet = compose_avatar(hair, face)
        out = OUT_DIR / "composite" / f"avatar_{hair}_{face}.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        sheet.save(out)

        scaled = sheet.resize((tile_w, SHEET_SIZE[1] * scale), Image.Resampling.NEAREST)
        x = (idx % 2) * tile_w
        y = (idx // 2) * tile_h
        preview.alpha_composite(scaled, (x, y))
        draw.text((x + 6, y + SHEET_SIZE[1] * scale + 4), f"{hair} + {face}", fill=(220, 220, 235, 255))

    preview.save(OUT_DIR / "_composite_preview.png")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    processed: list[Path] = []

    for path in sorted(RAW_DIR.rglob("*.png")):
        out = output_name(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        process_image(path).save(out)
        processed.append(out)
        print(f"{path.relative_to(RAW_DIR)} -> {out.relative_to(OUT_DIR)}")

    make_preview(processed)
    make_composite_preview()
    print(f"preview -> {(OUT_DIR / '_preview.png').relative_to(ROOT)}")
    print(f"composite preview -> {(OUT_DIR / '_composite_preview.png').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
