# Generated by Django 5.1.8 on 2026-06-15 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('score_delta', models.IntegerField(default=0)),
                ('stress_delta', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attempt_events',
                'ordering': ['occurred_at', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_token_hash', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SAFE_EXITED', 'Safe Exited'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('accumulated_score', models.IntegerField(default=0)),
                ('stress_index', models.IntegerField(default=0)),
                ('victim_risk', models.IntegerField(default=50)),
                ('user_trust', models.IntegerField(default=50)),
                ('institutional_route_activated', models.BooleanField(default=False)),
                ('revictimization_risk', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simulation_attempts_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context_json', models.TextField(default='{}')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('narrative_context', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.BigIntegerField(default=0)),
                ('world_schema_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'case_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clinical_tools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollisionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'collision_zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evidence_json', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'criterion_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('classification', models.CharField(choices=[('ADEQUATE', 'Adequate'), ('RISKY', 'Risky'), ('INADEQUATE', 'Inadequate')], max_length=20)),
                ('score_delta', models.IntegerField(default=0)),
                ('stress_delta', models.IntegerField(default=0)),
                ('prohibited_penalty', models.IntegerField(default=0)),
                ('immediate_feedback', models.TextField(default='')),
                ('prohibited_conduct', models.BooleanField(default=False)),
                ('prohibition_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decision_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DialogueChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_key', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('required_tool_code', models.CharField(blank=True, max_length=50, null=True)),
                ('effect_json', models.TextField(default='{}')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dialogue_choices',
                'ordering': ['display_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('speaker_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('emotion', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'dialogue_lines',
                'ordering': ['display_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DialogueTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_key', models.CharField(max_length=100)),
                ('speaker_name', models.CharField(max_length=255)),
                ('portrait_key', models.CharField(blank=True, max_length=100, null=True)),
                ('emotion', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dialogue_trees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=50)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('color_hex', models.CharField(default='', max_length=20)),
                ('icon', models.CharField(default='', max_length=50)),
                ('short_code', models.CharField(default='', max_length=20)),
                ('collision', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('interaction_prompt', models.CharField(default='', max_length=255)),
                ('interaction_text', models.TextField(default='')),
                ('tool_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unlock_condition_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('z_index', models.IntegerField(default=0)),
                ('facing', models.CharField(default='', max_length=20)),
                ('movement_pattern_json', models.TextField(default='{}')),
                ('metadata_json', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'map_objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publication_checklists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('evidence_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publication_checklist_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReflectionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.TextField()),
                ('encryption_key_ref', models.CharField(max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reflection_journals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rubrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rubric_criteria',
                'ordering': ['display_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rubric_evaluations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SceneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('theme', models.CharField(default='', max_length=100)),
                ('spawn_x', models.IntegerField(default=0)),
                ('spawn_y', models.IntegerField(default=0)),
                ('ambient_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scene_maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'simulation_cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('narrative', models.TextField()),
                ('support_resources_json', models.TextField(default='[]')),
                ('required_tools_json', models.TextField(default='[]')),
                ('sensitive_content', models.BooleanField(default=False)),
                ('safe_exit_required', models.BooleanField(default=False)),
                ('warning_message', models.TextField(blank=True, null=True)),
                ('start_node', models.BooleanField(default=False)),
                ('terminal_node', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(blank=True, default=0, null=True)),
                ('position_y', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'simulation_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttemptWorldState',
            fields=[
                ('attempt', models.OneToOneField(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='world_state', serialize=False, to='simulation.simulationattempt')),
                ('player_x', models.IntegerField(default=0)),
                ('player_y', models.IntegerField(default=0)),
                ('inventory_json', models.TextField(default='[]')),
                ('inspected_object_keys_json', models.TextField(default='[]')),
                ('viewed_dialogue_keys_json', models.TextField(default='[]')),
                ('used_tool_keys_json', models.TextField(default='[]')),
                ('flags_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attempt_world_states',
                'managed': False,
            },
        ),
    ]
