# Generated by Django 5.1.8 on 2026-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_rubric_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRubricAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulation_rubric_assignments',
                'managed': False,
            },
        ),
    ]
